name: Run Funds Scraper

on:
  workflow_dispatch: # Permite la ejecución manual desde la pestaña Actions
  schedule:
    - cron: '0 12 * * 1-5' # Ejecutar de lunes a viernes a las 12:00 PM UTC (aprox. 09:00 AM Chile)

jobs:
  scrape_funds:
    runs-on: ubuntu-latest

    steps:  # <--- Este es el bloque 'steps' principal para este job
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twilio requests beautifulsoup4 pandas nbconvert

    - name: Execute notebook
      run: |
    # Reemplaza 'your_notebook_name.ipynb' con el nombre exacto de tu archivo de notebook en GitHub
    jupyter nbconvert --to script FFMM.ipynb # Convierte el notebook a un script Python
    python your_notebook_name.py # Ejecuta el script Python
    env:
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }} # Si configuraste este secreto en GitHub
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}   # Si configuraste este secreto en GitHub
