name: Run Funds Scraper

on:
  workflow_dispatch: # Permite la ejecución manual
  schedule:
    - cron: '0 12 * * 1-5' # Ejecutar de lunes a viernes a las 12:00 PM UTC (09:00 AM Chile)

jobs:
  scrape_funds:
    runs-on: ubuntu-latest

    steps:
      # ... tus pasos aquí ...

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twilio selenium webdriver_manager requests beautifulsoup4 pandas smtplib nbconvert google-colab

    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute your_notebook_name.ipynb --stdout

    # Optional: Add steps to commit and push the updated CSV
    # - name: Commit and push updated data
    #   run: |
    #     git config user.name 'github-actions[bot]'
    #     git config user.email 'github-actions[bot]@users.noreply.github.com'
    #     git add valores_cuota_todos_fondos_*.csv
    #     git commit -m "Update fund values [skip ci]" || echo "No changes to commit"
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided
